### ISSUE TITLE
wallet address is returned instead of codeId on deploy

### ISSUE THREAD

**Issue by luca992** [digiline-io/Secret-IDE-Plugin#5]
The wallet address returned instead of codeId on deploy to pulsar-2
```
(base) lucaspinazzola@Lucas-MBP eqoty-secret-dapp % codeId=$(secretcli tx compute store contract.wasm.gz --from SecretIDE-Deployment --gas 937956 -y | jq '.logs[0].events[0].attributes[3].value')
(base) lucaspinazzola@Lucas-MBP eqoty-secret-dapp % echo "Contract stored successfully! Code ID: $codeId"
Contract stored successfully! Code ID: "secret1fdkdmflnrysrvg3nc4ym7zdsn2rm5atszn9q2y"
```

**Comment by dannym-arx** [comment]
I’ll push an extension update and new docks image) to fix that tomorrow (tho it may take up to 2 days to show up), thanks for reporting it :)

**Comment by luca992** [comment]
@thelmuxkriovar fyi not seeing the update, just letting you know in case something went wrong.

**Comment by dannym-arx** [comment]
sorry about that, the updated docker image should be up and the plugin is currently in review :)
